//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0-b170531.0717 
//         See <a href="https://jaxb.java.net/">https://jaxb.java.net/</a> 
//         Any modifications to this file will be lost upon recompilation of the source schema. 
//         Generated on: 2019.06.13 at 04:19:56 PM CST 
//


package main.java.statement;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the deskera.fintech.statement package.
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Statement_QNAME = new QName("deskera:fintech:statement:001", "Statement");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: deskera.fintech.statement
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link main.java.statement.DeskeraStatement }{@code >}
     *
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link main.java.statement.DeskeraStatement }{@code >}
     */
    @XmlElementDecl(namespace = "deskera:fintech:statement:001", name = "Statement")
    public JAXBElement<main.java.statement.DeskeraStatement> createStatement(
        main.java.statement.DeskeraStatement value) {
        return new JAXBElement<>(_Statement_QNAME, DeskeraStatement.class, null, value);
    }

}
